---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: source-lister
spec:
  params:
    - name: contextDir
      description: 'The context directory within the repository for sources'
      default: apps/greeter/java/quarkus
  resources:
    inputs:
      - name: source
        type: git
  steps:
    - name: ls-build-sources
      image: busybox
      command: ['ls', '-ltr', '/workspace/source/$(inputs.params.contextDir)']
